# Generated by Django 4.0.5 on 2022-06-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSystem', '0002_alter_tblavtor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblavtor',
            name='owner',
            field=models.TextField(),
        ),
    ]
