# Generated by Django 4.0.5 on 2022-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSystem', '0004_alter_tblavtor_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblavtor',
            name='adress_perepiski',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='avtor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='city_avtor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='date_av',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='date_place_public',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='name_work',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='num_av',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='oap',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblavtor',
            name='pseudonym',
            field=models.TextField(),
        ),
    ]
