# Generated by Django 4.0.5 on 2022-06-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSystem', '0005_alter_tblavtor_adress_perepiski_alter_tblavtor_avtor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmarkniceclasses',
            name='id_mark',
        ),
        migrations.AlterField(
            model_name='ipmarkniceclasses',
            name='registration_nbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchSystem.ipmark'),
        ),
    ]
