# Generated by Django 4.0.5 on 2022-07-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSystem', '0006_remove_ipmarkniceclasses_id_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmarkniceclasses',
            name='registration_nbr',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='id_nmpt',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='in_number',
            field=models.CharField(max_length=20, verbose_name='Входящий номер'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k11',
            field=models.CharField(max_length=20, verbose_name='Номер свидетельства'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k15',
            field=models.CharField(max_length=256, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k18',
            field=models.CharField(max_length=256, verbose_name='Дата истечения срока дейтсвия'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k21',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k22',
            field=models.CharField(max_length=256, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k46',
            field=models.CharField(max_length=256, verbose_name='№/Год публикации'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k54',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k57',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k71',
            field=models.CharField(max_length=256, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k73',
            field=models.TextField(verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='k98',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='remark_nmpt',
            field=models.TextField(verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='status_nmpt',
            field=models.IntegerField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tblnmpt',
            name='vid_tovara',
            field=models.TextField(verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='app_t',
            field=models.CharField(max_length=256, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='avtor_t',
            field=models.CharField(max_length=128, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='contact_t',
            field=models.CharField(max_length=256, verbose_name='Контактные данные правообладателя'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='date_place_t',
            field=models.CharField(max_length=128, verbose_name='Дата и место первого выпуска в свет ТИМС'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='date_svid_t',
            field=models.CharField(max_length=128, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='id_tims',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='in_date_t',
            field=models.CharField(max_length=128, verbose_name='Дата подачи заявления'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='in_number_t',
            field=models.CharField(max_length=128, verbose_name='Входящий номер'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='name_t',
            field=models.CharField(max_length=256, verbose_name='Название ТИМС'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='num_svid_t',
            field=models.CharField(max_length=128, verbose_name='№ свидетельства'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='number_reg_t',
            field=models.CharField(max_length=128, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='owner_t',
            field=models.CharField(max_length=256, verbose_name='Правообладатель'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='referat_t',
            field=models.TextField(verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='tbltims',
            name='status_tims',
            field=models.IntegerField(verbose_name='Статус'),
        ),
    ]
